FROM ubuntu:18.04

USER root
WORKDIR /home/root

# common depenency
#COPY sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y build-essential wget vim lsb-core software-properties-common

# install llvm 6
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
RUN apt-get update
RUN apt install -y clang-6.0
RUN ln -s /usr/bin/clang-6.0 /usr/bin/clang && ln -s /usr/bin/llvm-link-6.0 /usr/bin/llvm-link

RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt install -y python3.7 && \
apt install -y python3-pip && python3.7 -m pip install --upgrade pip
RUN rm /usr/bin/python && ln -s /usr/bin/python3.7 /usr/bin/python && \
rm /usr/local/bin/pip && ln -s /usr/local/bin/pip3.7 /usr/local/bin/pip

RUN pip install networkx && pip install matplotlib &&  pip install graphviz

RUN ln -s /mnt/llbic llbic && ln -s /mnt/build build
